name: dog

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dog
      run: mkdir ~/bin; wget -O ~/bin/dog https://raw.githubusercontent.com/rasmus-toftdahl-olesen/dog/master/dog.py; chmod +x ~/bin/dog
    - name: dog version
      run: ~/bin/dog --version
    - uses: actions/checkout@v2
    - name: cmake
      run: ~/bin/dog cmake .
    - name: make
      run: ~/bin/dog make
