name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake .
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: compile
      run: msbuild libSequantoAutomation.sln # /build Debug
